---
functional:
  - требование 1 Сайт должен предоставлять своим пользователям возможность регистрироваться, введя свои учетные данные
  - требование 2 Сайт должен предоставлять возможность одновременно двум пользователям выполнять одну задачу на разных языках программирования
  - требование 3 Сайт должен позволять играть с любым человеком, с ботом или другом 
  - требование 4 Сайт должен предоставлять  выбор  игры по уровню сложности
non-functional:
  - требование 3 Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - требование 4 Сайт должен быть безопасным и защищать данные пользователя
implicit:
  - требование 5 Сайт должен быть удобным на мобильном устройстве
  - требование 6 Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  
  
